name: STAS CI/CD Pipeline
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    runs-on: ubuntu-latest 
    
    steps:
    - name: Checkout code (Завантажити твій код)
      uses: actions/checkout@v4

    - name: Setup Node.js (Встановити Node.js)
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install dependencies (Встановити бібліотеки)
      run: npm install
      
    - name: Run Tests (Запустити тести)
      run: npm test

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Docker Hub (Залогінитись у Docker)
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push (Зібрати і відправити)
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/stas-project:latest
